// Package agent defines interfaces and data transfer models for AI coding agent runners.
//
// ==============================================================================
// ARCHITECTURAL ROLE & PATTERNS:
// Worker Abstraction Layer — Strategy Pattern.
//
// In Garagefab, AI coding agents (such as Google Antigravity `agy`, OpenCode, or
// test doubles like `FakeRunner`) are treated as swappable execution strategies.
// The factory orchestrator dispatches work via the `Runner` interface without knowing
// which specific agent implementation is active.
//
// GO CONCEPTS & JAVA COMPARISONS:
//
//  1. Function Types as Callbacks (`ProcessStartFunc`):
//     In Java, you would define an interface like `@FunctionalInterface public interface
//     ProcessStartListener { void onStart(int pid, int pgid, long startTime); }`.
//     In Go, functions are first-class citizens. You declare a function type directly:
//     `type ProcessStartFunc func(pid, pgid int, startTime int64)`.
//
//  2. Struct-Based Parameter Objects:
//     Instead of long method parameter lists, Go programs bundle parameters into request
//     and result structs (`AgentRequest`, `AgentResult`). This enables clean evolution
//     of parameters without breaking API signatures.
//
// ==============================================================================
package agent

import (
	"context"
	"errors"
	"time"
)

// ErrAgentUnavailable is returned when an agent runner is not registered, or its underlying binary
// cannot be found or executed (e.g. exec.ErrNotFound, permission denied).
var ErrAgentUnavailable = errors.New("worker/agent: agent unavailable")

// ProcessStartFunc is a callback invoked immediately after an agent subprocess starts.
// It reports the OS Process ID (PID) and Process Group ID (PGID) to the caller so
// they can be persisted to the database for crash recovery (RCV-1).
type ProcessStartFunc func(pid, pgid int, startTime int64)

// AgentRequest encapsulates all inputs needed to execute a single pipeline stage with an AI agent.
type AgentRequest struct {
	JobID          int64             // ID of the job being processed
	Stage          string            // Current SDLC pipeline stage (e.g. "04_Coding", "05_Independent_Review")
	Role           string            // SDLC role being executed (e.g. "coding", "spec", "review")
	Agent          string            // Concrete agent name (e.g. "agy", "opencode", "fake")
	WorktreePath   string            // Absolute path to the isolated git worktree where the agent will work
	Prompt         string            // The instruction or task specification for the agent
	ProjectName    string            // Name of the project repository
	Env            map[string]string // Environment variables passed to the agent process
	LogPath        string            // Destination file path for streaming process logs
	Timeout        time.Duration     // Maximum execution duration before SIGTERM/SIGKILL
	OnProcessStart ProcessStartFunc  // Optional callback fired once the OS process has launched
}

// Usage records token metrics reported by the agent model (informational).
type Usage struct {
	PromptTokens     int // Tokens consumed by the input prompt
	CompletionTokens int // Tokens generated by the model response
	TotalTokens      int // Cumulative token count
}

// AgentResult represents the outcome and produced artifacts of an agent run.
type AgentResult struct {
	ExitCode     int           // OS process exit code (0 indicates success)
	ArtifactPath string        // Path to structured JSON artifact produced by the agent (e.g. review.json)
	Summary      string        // Human-readable summary of actions taken by the agent
	TimedOut     bool          // True if process was terminated due to timeout
	Cancelled    bool          // True if process was terminated due to parent context cancellation
	Duration     time.Duration // Wall-clock execution time
	Usage        Usage         // Optional token counts, informational only
}

// Runner is the common interface implemented by all AI coding agent adapters.
//
// Go Concept: Implicit Interfaces.
// Any struct providing a `Run(context.Context, AgentRequest) (*AgentResult, error)`
// method automatically satisfies this interface without needing an `implements` declaration.
type Runner interface {
	Run(ctx context.Context, req AgentRequest) (*AgentResult, error)
}
