run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports

linters-settings:
  govet:
    enable-all: false
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-dirs:
    - ui
    - bin
