// Package garagefab provides the root package and exposes the embedded frontend assets.
//
// ==============================================================================
// ARCHITECTURAL ROLE & PATTERNS:
// Single-Binary Distribution & Embedded Web Assets.
//
// Garagefab is designed to be distributed as a single standalone executable binary
// (`CGO_ENABLED=0`) containing both the backend Go daemon and the React frontend SPA.
//
// GO EMBED CONCEPTS & JAVA / SPRING COMPARISON:
//
// 1. `//go:embed` Directive:
//   - In Java/Spring Boot, frontend assets are built into `src/main/resources/static/`
//     and packed inside the executable `.jar` (a ZIP archive). At runtime, Spring's
//     `ResourceHttpRequestHandler` loads them via `ClassLoader.getResourceAsStream()`.
//   - In Go, `//go:embed` (introduced in Go 1.16) is a compiler directive (pragma).
//     During compilation, the Go compiler scans the referenced directory (`ui/dist`),
//     reads all files, and compiles their raw byte contents directly into the binary's
//     read-only data segment (`.rodata`).
//   - The resulting binary requires NO external asset folders, web servers, or zip files.
//
// 2. `embed.FS` and `io/fs.FS`:
//   - `embed.FS` implements Go's standard `io/fs.FS` interface (virtual filesystem).
//   - `fs.Sub(distFS, "ui/dist")` creates a sub-tree rooted at `ui/dist`, allowing the
//     HTTP file server to serve `/index.html` directly without exposing the `ui/dist/`
//     prefix in URL routing.
//
// ==============================================================================
package garagefab

import (
	"embed"
	"io/fs"
)

// distFS embeds the entire production React build directory generated by `npm run build`.
// The "all:" prefix ensures hidden dotfiles (like .vite) are also included if present.
//
//go:embed all:ui/dist
var distFS embed.FS

// Dist returns an io/fs.FS filesystem rooted at the `ui/dist` directory.
//
// This allows the HTTP server (`internal/server/server.go`) to mount the embedded
// assets directly onto the HTTP handler via `http.FileServer(http.FS(Dist()))`.
func Dist() fs.FS {
	// fs.Sub strips the leading "ui/dist" directory from paths.
	// E.g., "ui/dist/index.html" becomes accessible as "index.html".
	sub, err := fs.Sub(distFS, "ui/dist")
	if err != nil {
		// Panic is intentional here: failing to find embedded files indicates
		// a build-time packaging bug, which must halt execution immediately.
		panic(err)
	}
	return sub
}
