// Package factory implements domain models, validators, and pipeline orchestration.
//
// ==============================================================================
// ARCHITECTURAL ROLE & DOMAIN SPECIFICATION:
// Domain Service / Pure Review Report Validator (Clean Architecture Core, REV-2, spec §6.2).
//
// Role:
// Validates structured critique artifacts (`review.json`) generated by the independent
// review agent in stage `05_Independent_Review`. Ensures schema versioning, valid decision
// enums, risk scoring boundaries (1..5), finding severity rules, and consistency
// (e.g. 'approve' decisions must not contain 'blocking' findings).
//
// ENTERPRISE & JAVA / SPRING COMPARISON:
// In Spring Boot: Similar to Jackson deserialization combined with Hibernate Validator
// constraints (`@NotNull`, `@Min(1)`, `@Max(5)`, custom class-level validator `@AssertTrue`).
// In Go: We deserialize JSON into strongly-typed domain structs and perform pure functional
// validations without runtime reflection or annotation processing.
//
// ==============================================================================
package factory

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

var (
	// ErrReviewBadJSON indicates invalid JSON syntax in review.json.
	ErrReviewBadJSON = errors.New("review: invalid JSON syntax")
	// ErrReviewInvalidVersion indicates schema_version is not 1.
	ErrReviewInvalidVersion = errors.New("review: schema_version must be 1")
	// ErrReviewInvalidDecision indicates decision is neither 'approve' nor 'request_changes'.
	ErrReviewInvalidDecision = errors.New("review: decision must be 'approve' or 'request_changes'")
	// ErrReviewEmptySummary indicates summary is empty.
	ErrReviewEmptySummary = errors.New("review: summary cannot be empty")
	// ErrReviewInvalidScore indicates a risk score is outside the 1–5 range.
	ErrReviewInvalidScore = errors.New("review: risk score must be an integer between 1 and 5")
	// ErrReviewEmptyRationale indicates a risk dimension has an empty rationale.
	ErrReviewEmptyRationale = errors.New("review: risk rationale cannot be empty")
	// ErrReviewInvalidSeverity indicates finding severity is neither 'blocking' nor 'minor'.
	ErrReviewInvalidSeverity = errors.New("review: finding severity must be 'blocking' or 'minor'")
	// ErrReviewBlockingApproval indicates an 'approve' decision contains a blocking finding.
	ErrReviewBlockingApproval = errors.New("review: decision 'approve' cannot contain blocking findings")
	// ErrReviewInvalidCoverage indicates spec coverage status is not 'met', 'partial', or 'not_met'.
	ErrReviewInvalidCoverage = errors.New("review: coverage status must be 'met', 'partial', or 'not_met'")
)

// ReviewRiskItem represents a single evaluated risk dimension with score and rationale (§6.2).
type ReviewRiskItem struct {
	Score     int    `json:"score"`
	Rationale string `json:"rationale"`
}

// ReviewRisk captures the three required SDLC risk assessment dimensions (§6.2).
type ReviewRisk struct {
	SideEffect            ReviewRiskItem `json:"side_effect"`
	Performance           ReviewRiskItem `json:"performance"`
	BackwardCompatibility ReviewRiskItem `json:"backward_compatibility"`
}

// ReviewFinding represents a scope-bound defect in the changed code (§6.2).
type ReviewFinding struct {
	Severity    string `json:"severity"` // "blocking" | "minor"
	File        string `json:"file"`
	Line        int    `json:"line"`
	Description string `json:"description"`
}

// ReviewWarning represents an out-of-scope technical debt or pre-existing observation (§6.2, REV-3).
type ReviewWarning struct {
	File        string `json:"file"`
	Description string `json:"description"`
}

// ReviewCoverage records the verification status of a job spec acceptance criterion (§6.2).
type ReviewCoverage struct {
	Criterion string `json:"criterion"`
	Status    string `json:"status"` // "met" | "partial" | "not_met"
	Note      string `json:"note"`
}

// ReviewReport represents the complete parsed and validated review.json data contract (§6.2).
type ReviewReport struct {
	SchemaVersion int              `json:"schema_version"`
	Decision      string           `json:"decision"` // "approve" | "request_changes"
	Summary       string           `json:"summary"`
	Risk          ReviewRisk       `json:"risk"`
	Findings      []ReviewFinding  `json:"findings"`
	Warnings      []ReviewWarning  `json:"warnings"`
	SpecCoverage  []ReviewCoverage `json:"spec_coverage"`
}

// ValidateReviewJSON parses and enforces data contract invariants on review.json (REV-2, spec §6.2).
//
// Rules enforced:
// 1. Valid JSON adhering to schema_version == 1.
// 2. Decision is either "approve" or "request_changes".
// 3. Risk dimensions (side_effect, performance, backward_compatibility) each have score in [1, 5] and non-empty rationale.
// 4. Finding severity is either "blocking" or "minor".
// 5. Rule REV-2: If decision is "approve", findings MUST NOT contain any "blocking" item.
// 6. Spec coverage statuses must be "met", "partial", or "not_met".
func ValidateReviewJSON(data []byte) (*ReviewReport, error) {
	if len(strings.TrimSpace(string(data))) == 0 {
		return nil, errors.New("review: empty content")
	}

	var report ReviewReport
	if err := json.Unmarshal(data, &report); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrReviewBadJSON, err)
	}

	if report.SchemaVersion != 1 {
		return nil, fmt.Errorf("%w: got %d", ErrReviewInvalidVersion, report.SchemaVersion)
	}

	if report.Decision != "approve" && report.Decision != "request_changes" {
		return nil, fmt.Errorf("%w: got %q", ErrReviewInvalidDecision, report.Decision)
	}

	if strings.TrimSpace(report.Summary) == "" {
		return nil, ErrReviewEmptySummary
	}

	// Validate risk dimensions
	validateRisk := func(name string, item ReviewRiskItem) error {
		if item.Score < 1 || item.Score > 5 {
			return fmt.Errorf("%w for %s: got %d", ErrReviewInvalidScore, name, item.Score)
		}
		if strings.TrimSpace(item.Rationale) == "" {
			return fmt.Errorf("%w for %s", ErrReviewEmptyRationale, name)
		}
		return nil
	}

	if err := validateRisk("side_effect", report.Risk.SideEffect); err != nil {
		return nil, err
	}
	if err := validateRisk("performance", report.Risk.Performance); err != nil {
		return nil, err
	}
	if err := validateRisk("backward_compatibility", report.Risk.BackwardCompatibility); err != nil {
		return nil, err
	}

	// Validate findings and check blocking constraint (REV-2)
	for i, f := range report.Findings {
		sev := strings.ToLower(strings.TrimSpace(f.Severity))
		if sev != "blocking" && sev != "minor" {
			return nil, fmt.Errorf("%w at index %d: got %q", ErrReviewInvalidSeverity, i, f.Severity)
		}
		if report.Decision == "approve" && sev == "blocking" {
			return nil, fmt.Errorf("%w: finding on %s:%d is blocking", ErrReviewBlockingApproval, f.File, f.Line)
		}
	}

	// Validate spec coverage
	for i, c := range report.SpecCoverage {
		st := strings.ToLower(strings.TrimSpace(c.Status))
		if st != "met" && st != "partial" && st != "not_met" {
			return nil, fmt.Errorf("%w at index %d: got %q", ErrReviewInvalidCoverage, i, c.Status)
		}
	}

	if report.Findings == nil {
		report.Findings = []ReviewFinding{}
	}
	if report.Warnings == nil {
		report.Warnings = []ReviewWarning{}
	}
	if report.SpecCoverage == nil {
		report.SpecCoverage = []ReviewCoverage{}
	}

	return &report, nil
}
